### ISSUE TITLE
Add a way for the client to manage the default avatar colors

### ISSUE THREAD

**Issue by sweko** [HaithemMosbahi/ngx-avatar#10]
Currently, the colors for the generated avatars are internal to the application.
While it is possible to use

```
        import { defaultColors } from "ngx-avatar";
        defaultColors.splice(0, defaultColors.length);
        defaultColors.push("red", "green", "blue");
```

to change them, this has a hacky feel to it.
There should be a nicer, more straightforward way to set the avatar colors.

**Comment by HaithemMosbahi** [comment]
Yes that's a good idea. Actually, when I started the development of ngx-avatar I thought of a default set of colors to fill the avatar when the user does not provide a backgroundColor. Thus, I didn't expect the defaultColors to be consumed and changed by the developer.
I totally agree with you, we should think of a more convenient way to set the default avatar colors.

**Comment by sweko** [comment]
This is a feature I actually need, as I'll be showing a lot of avatars, most of the generated - so I want them to  have colors that are in line with the overall color scheme of the application.

**Comment by HaithemMosbahi** [comment]
Yes. I've got an idea that will allow the developer to manage and change the default colors. I will share it with you

**Comment by HaithemMosbahi** [comment]
Hello @sweko,
I have been thinking of passing the array of default colors when you import the AvatarModule. So If you would like to provide your own set of colors, the import of AvatarModule would look like this : 
```ts 
AvatarModule.forRoot(arrayOfColors)
```
Something similar to the RouterModule of Angular when we pass the array of routes.
What do you think ?

**Comment by sweko** [comment]
I like that very much.
Maybe we can make it a configuration object so that we can add other settable properties later?

**Comment by HaithemMosbahi** [comment]
Yes I agree with you, we will probably need to pass additional informations in the future. I will make it a configuration Object

**Comment by HaithemMosbahi** [comment]
Hey @sweko 
I have just released a new version that has support for overriding avatar option. 
Here is an example of how the import of avatar module with your own configuration would look like : 

https://github.com/HaithemMosbahi/ngx-avatar/blob/c0380cd027095d15c4b8de92261369bad23e068c/demo/src/app/app.module.ts#L5-L24

Check out the documentation section : Override Avatar Configuration
I am waiting for your feedback 😃

**Comment by sweko** [comment]
Tnx, I've just gotten around to updating it, and it works fine.
