### ISSUE TITLE
Use HttpClientModule from Angular 4.3+

### ISSUE THREAD

**Issue by Shinzah** [HaithemMosbahi/ngx-avatar#12]
Could you use the new Http module from angular 4.3+ @angular/common/http (HttpClientModule) instead of @angular/http (HttpModule) ?

**Comment by HaithemMosbahi** [comment]
Yes I can totally consider this feature. However, ngx-avatar is intended to be used with angular versions 4.X.X and the new HttpClientModule module requires Angular 4.3 and above.
If my understanding is correct, I think migrating to the new HttpClientModule will cause applications with version < 4.3 to fail.

**Comment by Dunos** [comment]
Do you plan to update the library for the latest Angular 5 version?

**Comment by sarfarazansari** [comment]
@HaithemMosbahi you are absolutely right.
but we can make a plan to work this plugin in angular 5 apps. If you agree am ready for a PR

**Comment by minuz** [comment]
@HaithemMosbahi, Is there any particular reason why you want to keep supporting version 4.x.x?
They are close to release version 6 so it would be interesting to keep the library updated.
In addition, for those users who didn't upgrade to the current version of Angular, they can always keep using an older version of the library. Maybe branch it off to provide specific bug fixes.
Btw, I'm happy to help with the upgrade process if you need.

**Comment by HaithemMosbahi** [comment]
@minuz @sarfarazansari I am really sorry for the late reply guys.
I totally agree to upgrade the library to use the latest features of Angular platform. I wasn't active in the last few months due to some personal reasons. Nevertheless I am back now and I am planning to resolve the issues and upgrade the library as soon as possible.

**Comment by HaithemMosbahi** [comment]
This should be fixed with the latest release 3.0.0
