### ISSUE TITLE
Release with latest Angular support

### ISSUE THREAD

**Issue by Heatmanofurioso** [HaithemMosbahi/ngx-avatar#121]
Hi @HaithemMosbahi. Any possible ETA on the release of the latest changes?
If there is any issue, or anything I can help with towards it, I'd gladly take up any issue

**Comment by odahcam** [comment]
Sorry, no ETA, Haithem is the only one who can release packages this moment.

**Comment by Heatmanofurioso** [comment]
He seemed to stop being active a while after a year ago.

I hate to say this, but should we maybe consider forking and continuing the package ourselves? I've sent him an email around a month ago asking about the dependency updates before I decided to do them myself, but he didn't answer.

And I think that, with the due reference, we should consider continuing the project ourselves @odahcam

**Comment by odahcam** [comment]
Yeah, this is a recorrent question now. I won't be an active contributor as well, but I can in fact help maintain. @PowerKiKi is a good contributor and his opinion matters in that question.

**Comment by PowerKiKi** [comment]
@Heatmanofurioso, we've been on the verge of forking a few months ago, but [have been saved in extremis](https://github.com/HaithemMosbahi/ngx-avatar/issues/93#issuecomment-638254015). But since then, the whole thing died down again. So I recently made up my mind to [migrating away from this lib](https://github.com/HaithemMosbahi/ngx-avatar/pull/113#issuecomment-740349327). My opinion on things didn't change since then.

**Comment by Heatmanofurioso** [comment]
I don't see myself having much time to be a main contributor, but I could easily also take part in helping maintain the library.

I think the library has some decent potential to be kept alive, and the biggest issue in forking it would probably be bringing attention to the forked version. "That, and  I'd like to avoid it as much as possible, since I am a strong supporter of not trying to take ownership of something I shouldn't. But HaithemMosbahi seems to have gone inactive, and I think it's what we should do".

@odahcam Would you like to take ownership of it then? Or should I if no one else volunteers?

**Comment by odahcam** [comment]
I would take ownership if needed, no problem. But I would just maintain the repsitory and probably wouldn't implement many things.

**Comment by Heatmanofurioso** [comment]
Sounds great @odahcam!
Anyway, I was able to reach HaithemMosbahi through other means "I believe I wasn't too invasive/bothersome". He said he'll try and get some time to help us out with this issue, so let's wait for a reply on his side once he has time for it :)

**Comment by PowerKiKi** [comment]
If you can get a hold of HaithemMosbahi, I strongly suggest you ask for total control on this repository and the related npm registry (for one or both of you guys), or else fork the whole project. Anything else would be a waste of time for both parties.

**Comment by mhosman** [comment]
Yeah, we need someone else to keep updating this repo. @HaithemMosbahi can you please give access to other people to improve this library? That would be great! Thanks!

**Comment by rwdroge** [comment]
fingers crossed...

**Comment by Heatmanofurioso** [comment]
Well. Apparently the owner hasn't had time to reach out to us and help us out with this after that initial talk.
Do you guys think it's worth trying to reach out to him again, or should we fork this with the correct reference?

As I said.. I'm not much in favour of "taking someone's work", but in the open-source spirit, I would like to maintain this project, and also to keep on using it
@odahcam @mhosman @PowerKiKi

**Comment by PowerKiKi** [comment]
Fork right now, with the appropriate attribution, and be done with it. The MIT license allows you do pretty much anything you want. And it's been months that several people tried to establish a working collaboration, but it never happened, because the owner did not share enough accesses. Fork, rename, make a respectful announcement around here, and move the community to something that is maintained (collaboratively).

**Comment by mhosman** [comment]
We can create a package **ngx-avatars** (plural) and that's it.

**Comment by Heatmanofurioso** [comment]
Anyone opposes on me making a fork on that namespace and attempting to make the package on npm?
Or anyone else wishes to take it?

**Comment by Heatmanofurioso** [comment]
Also... any suggestions for the name? 😆

**Comment by mhosman** [comment]
Just put ngx-avatars and let's give access to at least two contributors to the package (I'm saying, just to speed up things). If you need help please let me know.

**Comment by Heatmanofurioso** [comment]
The repo has been created at https://github.com/Heatmanofurioso/ngx-avatars
Please give a look on the PR guys

**Comment by Heatmanofurioso** [comment]
In case anyone is interested, the package is published and working at [ngx-avatars](https://www.npmjs.com/package/ngx-avatars)

**Comment by mhosman** [comment]
Maybe we could put a note in the README in this repo, telling that is deprecated and the project will continue as ngx-avatars.

**Comment by Heatmanofurioso** [comment]
@odahcam If you agree, could you see to it?

**Comment by HaithemMosbahi** [comment]
Hello guys, 

Sorry for not being active for a long period.

I just published a new version with the changes that you merged over the last months.

Who would be interested in being added to the npm package maintainers list, that way I don't block the release of new versions when I am not available.

**Comment by Heatmanofurioso** [comment]
Hi Haithem.
I'd like to be added.
If we feel like we can maintain this project, I'd much rather do that than have a clone.

I'll gladly deprecate that child project if we can keep this one up :)

**Comment by HaithemMosbahi** [comment]
Great!
Could you share with me your npm user name ? I will send you an invite 

Thank you for your help

**Comment by mhosman** [comment]
@PowerKiKi Can you please also share your npm user? It could be great to have at least 2 users in addition to @HaithemMosbahi

**Comment by PowerKiKi** [comment]
I am https://www.npmjs.com/~powerkiki. You should definitely add https://www.npmjs.com/~odahcam who has been helping here even longer than me, and https://www.npmjs.com/~heatmanofurioso who owns the new fork.

**Comment by HaithemMosbahi** [comment]
Sounds good!  I will add you as maintainers. 
Thanks a lot for your help and contributions

**Comment by HaithemMosbahi** [comment]
@PowerKiKi @odahcam @Heatmanofurioso I just added you as maintainers to the npm package. You should have received an invite by now.

**Comment by PowerKiKi** [comment]
I can confirm I have access, though somehow it is not visible publicly, probably some stale cache:

![image](https://user-images.githubusercontent.com/72603/113679770-19dfff00-96fb-11eb-9930-d9de3d8ba530.png)

**Comment by Heatmanofurioso** [comment]
Same here. Although I'm not sure if you show up as a collaborator only once you effectively collaborate "do a publish".
But that doesn't matter. 

Thank you for your time and attention @HaithemMosbahi 

I'm gonna do a PR taking Angular 11.2.x in consideration here "once I have time", and once we can support the latest version, I'm going to deprecate my forked project, and point it back here

**Comment by odahcam** [comment]
@HaithemMosbahi is there a way you can give us permissions to change the secrets of this repository? That would allow us to configure GitHub Actions to test and auto-release the master branch!

---

Edit: I forgot to thank you @HaithemMosbahi for giving us that privilege, thanks!

**Comment by PowerKiKi** [comment]
I recommend creating a GitHub org, transfer ownership of this repository to that org, and then increase access privilege (to admin) for some of us.

**Comment by Heatmanofurioso** [comment]
This convo seems to be addressed on #125 
Therefore, I'm closing this issue so we can approach the whole discussion there
