### ISSUE TITLE
Restrict to show 2 characters in avatar

### ISSUE THREAD

**Issue by eforteAdeel** [HaithemMosbahi/ngx-avatar#13]
Is there any option to restrict it to show just 2 characters in avatar?

**Comment by HaithemMosbahi** [comment]
Hello, 
The current version of ngx-avatar component does not have this feature. However, I think that it makes sense to add this restriction as input.
I will implement this feature and release a new version asap

**Comment by HaithemMosbahi** [comment]
This feature has been added in version 2.8.0.
I just added a new property **initialsSize**  to fix the number of characters for initials avatars.
Here's an example that restricts the avatar to render 2 characters : 
```html
<ngx-avatar  initialsSize="2"  name="John Johnson Doe"></ngx-avatar>
```

**Comment by eforteAdeel** [comment]
Thanks.
