### ISSUE TITLE
Add source priority list in AvatarConfig

### ISSUE THREAD

**Issue by manniniandrea** [HaithemMosbahi/ngx-avatar#14]
It could be very usefull if we could configure the priprity list

**Comment by HaithemMosbahi** [comment]
Hi,
Yes, I can totally consider adding this feature.
I will work on it and release a new version as soon as I can. If you need this urgently, feel free to make a pull request and I will be happy to merge it, You are very welcome to contribute :)

**Comment by HaithemMosbahi** [comment]
I will close this issue since it has been resolved
