### ISSUE TITLE
name with extra space

### ISSUE THREAD

**Issue by tomalex0** [HaithemMosbahi/ngx-avatar#17]
name with extra spaces breaks the  avatar preview, this can be  fixed from  my code if i take care of the extra spaces.
If you can  fix it as part of framework that will be great :)

`<ngx-avatar size="50" name="Haithem Mosbahi " ></ngx-avatar>` - `ending with extra space`
`<ngx-avatar size="50" name="Haithem  Mosbahi" ></ngx-avatar>` -  `extra space between the words`
`<ngx-avatar size="50" name=" Haithem Mosbahi" ></ngx-avatar>` -  ` leading extra space`

**Comment by HaithemMosbahi** [comment]
Hi, 
Thank you for raising this issue. I just published a new version ( 2.9.0 ) which fixes this issue.
