### ISSUE TITLE
Visual Studio Code error ngx-avatar has no exported member AvatarModule

### ISSUE THREAD

**Issue by SoumenDass** [HaithemMosbahi/ngx-avatar#19]
I'm able to use ngx-avatar fine but Visual Studio Code (version: 1.20.0-insider) shows this error:

`[ts] Module '"c:/User/abc/ui/node_modules/ngx-avatar/ngx-avatar"' has no exported member 'AvatarModule'.`

**Comment by ArthurMauricioDelgadillo** [comment]
Are you sure? I'm using VS code 1.19 and everything is working ok! 
Are you importing the AvatarModule ok? Or maybe is a bug in v1.20 in that case you should put your issue in vscode repo

**Comment by SoumenDass** [comment]
Yes the import is fine because the component is displaying and working correctly. This is the only error "no exported member" error I'm getting. It is possible that this is a VSCode bug - I'll wait if this goes away in their future releases.
