### ISSUE TITLE
how to change width and height of the avatar???????????????

### ISSUE THREAD

**Issue by hemanthsp** [HaithemMosbahi/ngx-avatar#20]
1).avatar .avatar-container{
    height:60px ;
    width: 60px ;
}

2) .avatar .avatar-content{
    height: 60px ;
    width:60px ;
} 

which one is correct?

**Comment by gabrieltbmaestro** [comment]
You could use the [size]="60" directive directly on ngx-avatar.

**Comment by hemanthsp** [comment]
nobody likes to put css into html directly right? so give some best solution

**Comment by minuz** [comment]
@hemanthsp with all due respect, but if you spend 2 min reading the documentation you would find what you are looking for.

In addition, the solution provided by @gabrieltbmaestro is the one described on the library docs.
https://github.com/HaithemMosbahi/ngx-avatar#options

**Comment by hemanthsp** [comment]
thx bro,this is your lib, i have to follows according to your lib

**Comment by minuz** [comment]
This is not my lib lol. But I have been using it and I like to contribute whenever I can.
