### ISSUE TITLE
Add caching which works across components

### ISSUE THREAD

**Issue by pfeigl** [HaithemMosbahi/ngx-avatar#25]
Currently ngx-avatar tries to load the same (not available) avatars over and over again, spamming the console and request log with 404s.

It would be very nice, if this component would cache which sources resulted in "Not Found" and not retry them. 

Especially as are within a SPA, it's unexpected to get the same errors multiple times.

**Comment by HaithemMosbahi** [comment]
I totally agree with. This would be a good feature 
I will consider adding a cache system in the next version

**Comment by strovato-fts** [comment]
Hello, I'm sorry if my question seems silly, but is it possible to catch those 404 errors and not display them in the console ?

thanks
