### ISSUE TITLE
Not Working with Angular2

### ISSUE THREAD

**Issue by brunoboss** [HaithemMosbahi/ngx-avatar#27]
Tried to install in a project that is using Angular2, of course the first error was the use of InjectionToken instead of OpaqueToken, but when changing InjectionToken to OpaqueToken i get "Can't resolve all parameters for AvatarComponent". What's the right branch or the right method in order to use this library with Angular 2 project? 

@HaithemMosbahi

**Comment by HaithemMosbahi** [comment]
Hi and sorry for the late reply. Unfortunately the current version requires angular 4+.
In case you still need the component for angular 2 project, you can try version 1.1.0
