### ISSUE TITLE
Not working with rxjs 6.0

### ISSUE THREAD

**Issue by ThaiHM** [HaithemMosbahi/ngx-avatar#32]
Not working with rxjs 6.0.

**Comment by sarfarazansari** [comment]
@ThaiHM, @HaithemMosbahi , @sweko 
am going to create a PR soon, for angular 6 compatible.

**Comment by sarfarazansari** [comment]
@ThaiHM , @sweko , @HaithemMosbahi 
take a look [PR](https://github.com/HaithemMosbahi/ngx-avatar/pull/33)

**Comment by Cloud925** [comment]
any update on this?

**Comment by mhosman** [comment]
Same issue here!

**Comment by HaithemMosbahi** [comment]
This should be fixed with version 3.0.0
