### ISSUE TITLE
Maintence status

### ISSUE THREAD

**Issue by odahcam** [HaithemMosbahi/ngx-avatar#34]
@HaithemMosbahi please add some maintainer if you won't maintain the package anymore, thx.

**Comment by HaithemMosbahi** [comment]
Hello, 
I'm back to maintain the project and I will make sure to add a maintainer to avoid this in the future

**Comment by HaithemMosbahi** [comment]
Hey @odahcam. Are you interested in maintaining the component with me ? That would be great :)

**Comment by odahcam** [comment]
I feel flattered about that, sure I can give some help. 🙂
