### ISSUE TITLE
App.Module import not working

### ISSUE THREAD

**Issue by Cloud925** [HaithemMosbahi/ngx-avatar#35]
Hi,

cant import the ngx-avatar module in my app.module. Then i get the error "Cannot find module 'testing'".

I installed the module from master with the git link with npm. I noticed that there are no *.d.ts files anymore 
after importing and the package.config changed a lot which could cause the problem.

Looks like the project name was changed to "testing" and version is changed to "0.0.0".

Could you please have a look at this?

**Comment by HaithemMosbahi** [comment]
Hi, 
Yes I'm working on it, I just merged a pull request to support angular 6 and there's still some work to do on the master. I'm doing my best to fix it and release a new version as soon as possible.

Also, the library has new structure based on Angular CLI.

**Comment by HaithemMosbahi** [comment]
This should be fixed in version 3.0.0. Please take a look on the latest release and let me know if you have any questions :)
