### ISSUE TITLE
Cover the component with unit test 

### ISSUE THREAD

**Issue by HaithemMosbahi** [HaithemMosbahi/ngx-avatar#38]
In order to improve the component code and to reduce potential bugs and also to make it easy to maintain we need to cover the ngx-avatar component with unit test.

**Comment by HaithemMosbahi** [comment]
I'm working on this one, I started by refactoring / covering the avatar.service. Here's the [branch](https://github.com/HaithemMosbahi/ngx-avatar/tree/feature/refactoring-and-testing)

**Comment by HaithemMosbahi** [comment]
should be closed when this branch gets merged #46

**Comment by odahcam** [comment]
I think it's ready, isn't it?

**Comment by HaithemMosbahi** [comment]
I still need to cover some scenarios in the avatar.component.spec.ts
The goal is to cover the maximum features to avoid bugs / regression. I think after that we will be able to confidently auto publish to npm when we merge to master
