### ISSUE TITLE
fix continuous integration build

### ISSUE THREAD

**Issue by HaithemMosbahi** [HaithemMosbahi/ngx-avatar#39]
This is about fixing the travis build

**Comment by odahcam** [comment]
Just to reference for future: https://travis-ci.org/HaithemMosbahi/ngx-avatar

**Comment by odahcam** [comment]
Let's start with #40

**Comment by odahcam** [comment]
@HaithemMosbahi can you help me on that?

```
Chromium 62.0.3202 (Ubuntu 0.0.0): Executed 1 of 1 (1 FAILED) (0 secs / 0.092 secs)
Chromium 62.0.3202 (Ubuntu 0.0.0) AvatarComponent should create FAILED
	Error: StaticInjectorError(DynamicTestModule)[AvatarComponent -> SourceFactory]: 
	  StaticInjectorError(Platform: core)[AvatarComponent -> SourceFactory]: 
	    NullInjectorError: No provider for SourceFactory!
```

**Comment by HaithemMosbahi** [comment]
@odahcam yes sure, the service SourceFactory must be provided to avatar.component spec. I'm going to update the pull request

**Comment by odahcam** [comment]
And success: https://travis-ci.org/HaithemMosbahi/ngx-avatar/builds/436514474

Once this doesn't depends on any release to take effect, I'm closing it.
