### ISSUE TITLE
Issue when attempting to build.

### ISSUE THREAD

**Issue by ravtakhar** [HaithemMosbahi/ngx-avatar#4]
Just want to start off by saying that this is absolutely amazing.

Have been using for about a week now it has saved me loads of development time. However, I just recently ran into an issue when attempting to build.

I get the following warning:
WARNING in ./src/$$_gendir/~/ngx-avatar/ngx-avatar.ngfactory.ts
271:44-54 "export 'ɵa' (imported as 'import1') was not found in 'ngx-avatar'

and I get the following error:
ERROR in ng:///H:/Code/Megatron/Client/node_modules/ngx-avatar/ngx-avatar.d.ts.AvatarComponent.html (4,5): Type 'string' is not assignable to type 'boolean'.

Thanks!

**Comment by HaithemMosbahi** [comment]
Hello, I'm glad this component has been helpful to you.

Thank you for raising this issue, I'm working on it.

**Comment by HaithemMosbahi** [comment]
Hello,
I've just released a new version ( 2.1.0 ) which fixes issues related to prod and AOT build.

**Comment by ravtakhar** [comment]
Thanks dude! 
Absolutely amazing works. Means a lot!
