### ISSUE TITLE
Update deps. to Angular 7.0

### ISSUE THREAD

**Issue by mhosman** [HaithemMosbahi/ngx-avatar#43]

**Comment by odahcam** [comment]
I'm on it!

**Comment by odahcam** [comment]
Looks like a package called `tsickle` is blocking the way for ng 7. We shall wait until that package adds support for TS 3.x 😞

**Comment by odahcam** [comment]
WIP PR opened #44

**Comment by HaithemMosbahi** [comment]
@mhosman we just release version 3.2.0 which includes upgrading angular dependencies to 7.0.0
