### ISSUE TITLE
Error when packaging with Webpack

### ISSUE THREAD

**Issue by bhalperin** [HaithemMosbahi/ngx-avatar#5]
Hi,

Using version 2.2.0 (latest). I get an error when my app loads:
![image](https://user-images.githubusercontent.com/683900/28971556-0d60c486-7935-11e7-9b99-f3d08263737c.png)

In one of my modules I did:
`import { AvatarModule } from "ngx-avatar";`
`@NgModule({
    imports: [... AvatarModule],`

Using Angular 4.3.0
Webpack (1.13.0) says **Compiled successfully**.

Any idea? Thanks!

**Comment by HaithemMosbahi** [comment]
Hello, 

Is this a regression ? Have you already used a previous version with your current environnement ?
unfortunately I couldn't reproduce your issue. As you can see in the demo folder, there's an angular application that demonstrates some examples of ngx-avatar component. This application use version 4.3.2 of angular and it works as expected.

Do you use angular cli ?

**Comment by bhalperin** [comment]
Hi,

Not a regression. It's my first experiment using ngx-avatar. I did not check your demo yet, but should to compare. Not using cli. Did you try w/o cli?

**Comment by HaithemMosbahi** [comment]
No, I did not try using ngx-avatar without Angular CLI.

**Comment by bhalperin** [comment]
The demo compiles and works well. It also bundles with webpack - probably angular cli default. The difference is that the demo bundle does not include the *import* lines that cause my app to fail. *Import* is unknown to the browser of course.

Any idea would be appreciated. TIA

**Comment by HaithemMosbahi** [comment]
Could you please share with me your application ? or do you have a link that describes how to create an angular application which uses the same config / bundle as yours.

**Comment by sweko** [comment]
You can take a look at this - error appears when I import the AvatarModule.
Seems that the angular compiler tries to load the `index.js` file and fails on the `import` syntax.

https://stackblitz.com/edit/angular-jlslsu?file=app%2Fapp.module.ts

**Comment by bhalperin** [comment]
Yes index.js is the issue. I added babel-loader in webpack config to do the job.

**Comment by HaithemMosbahi** [comment]
Hi, 
I'm sorry for my late reply.
I've just updated my build script and released a new version of ngx-avatar. Could you please check wether the issue is resolved when using version 2.2.1 ?

Thank you

**Comment by sweko** [comment]
Tnx, it's operational now

**Comment by HaithemMosbahi** [comment]
Great !
