### ISSUE TITLE
Tooltip?

### ISSUE THREAD

**Issue by chadbr** [HaithemMosbahi/ngx-avatar#52]
Would it be feasible to add a tooltip that shows the name / email / whatever info is convenient?

Thanks, Chad

**Comment by odahcam** [comment]
You can easily use other tools with this component, like [Angular Material Tooltip](https://material.angular.io/components/tooltip/overview); e.g.:

```html
<ngx-avatar [matTooltip]="username"></ngx-avatar>
```

Feel free to ask any more questions you may have and share your result if you like. 🙂
