### ISSUE TITLE
How to call ngx-avatar's getRandomColor

### ISSUE THREAD

**Issue by bhalperin** [HaithemMosbahi/ngx-avatar#54]
In my Angular 7 app I successfully integrated ngx-avatar 3.2.0. However, I can't find how to call `AvatarService.getRandomColor()`. In my component file I have:

```
import { AvatarService } from 'ngx-avatar/lib/avatar.service';
...
constructor(private avatarService: AvatarService) { }
...
const color = this.avatarService.getRandomColor(name);
```

But my compilation fails with the following error:

```
ERROR in some.component.ts
Module not found: Error: Can't resolve 'ngx-avatar/lib/avatar.service' in 'd:\projects\...'
```

**Comment by bhalperin** [comment]
I changed it as follows to make it work. But I don't think it was the author's intention:
```
import * as Avatar from 'ngx-avatar';
...
constructor(private avatarService: Avatar.ec) { }
...
const color = this.avatarService.getRandomColor(name);
```
Should be (but not working):
```
import { AvatarService } from 'ngx-avatar';
...
constructor(private avatarService: AvatarService) { }
...
const color = this.avatarService.getRandomColor(name);
```

**Comment by odahcam** [comment]
Did you imported the `AvatarModule` as: 

```typescript 
import { AvatarModule } from 'ngx-avatar';
```

?

**Comment by bhalperin** [comment]
@odahcam Yes I did. I successfully integrated it as you can see below. Only problem is how to correctly call `getRandomColor`
![image](https://user-images.githubusercontent.com/683900/53855169-3158d500-3fd5-11e9-96e9-975491dfd293.png)

**Comment by odahcam** [comment]
Well, the `AvatarService` is not in the public API, so I'm afraid it is not intended to be used outside the lib itself. :/

**Comment by bhalperin** [comment]
Possibly. Anyway I upgraded from an older version of `ngx-avatar` where I had called it in a similar way like below:
```
import * as Avatar from 'ngx-avatar';
...
const color = Avatar.getRandomColor(name);
```
The reasoning is to retrieve the same color of my avatar in order to color e.g. a label I display next to it and wish to color same.

**Comment by odahcam** [comment]
Well, in this case I think `color` could be a `ngx-avatar` component's output, so you could get the current value directly from the component.

**Comment by bhalperin** [comment]
Thanks. So for now it's an enhancement request to the author.

**Comment by HaithemMosbahi** [comment]
Hi @bhalperin 
FYI, I just published a new version of ngx-avatar which exports the service, defaultColors and defaultSources.

**Comment by orahul1** [comment]
@HaithemMosbahi is this still open?

**Comment by odahcam** [comment]
Nope, `avatarService` is now public and the requested method is API available.
