### ISSUE TITLE
Update deps. to Angular 8.0

### ISSUE THREAD

**Issue by mhosman** [HaithemMosbahi/ngx-avatar#64]

**Comment by jpike88** [comment]
@odahcam can you guys just lock it in asap, I've been on the angular 8 betas since the beginning and there are no issues.

**Comment by mhosman** [comment]
Hey @jpike88 this is in order to remove the warning:
`ngx-avatar@3.5.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by jpike88** [comment]
@mhosman that's correct

**Comment by jpike88** [comment]
@mhosman any movement?

**Comment by HaithemMosbahi** [comment]
I am going to do the update and release a new version today

**Comment by jpike88** [comment]
i never saw that new version lol

**Comment by HaithemMosbahi** [comment]
A new version is released with Angular 8 support. I am sorry for the delay
