### ISSUE TITLE
CRITICAL: Module won't resolve on version 3.6.0

### ISSUE THREAD

**Issue by jpike88** [HaithemMosbahi/ngx-avatar#66]
@HaithemMosbahi Latest version is broken. Unable to import the module with latest version. see the stackblitz:

https://stackblitz.com/edit/ngx-avatar-demo-zdqn85

Downgrading to 3.5.0 works.

**Comment by HaithemMosbahi** [comment]
I did a mistake when I published version 3.6.0. Thank you for raising the issue.
I just fixed it, please use version 3.7.0
