### ISSUE TITLE
Add github avatar provider

### ISSUE THREAD

**Issue by sweko** [HaithemMosbahi/ngx-avatar#7]
Add a source for GitHub avatar pictures.

**Comment by HaithemMosbahi** [comment]
Hello,
Yes I can totally consider adding Github for fetching user's avatar. If you need this enhancement ASAP you are very welcome to contribute :)

**Comment by sweko** [comment]
Yes, I've added it, I'll run some checks and will PR it later.

**Comment by HaithemMosbahi** [comment]
Great !

**Comment by HaithemMosbahi** [comment]
Fixed #8 
This feature has been included in version 2.3.0
