### ISSUE TITLE
Update dependencies to Angular 9.0

### ISSUE THREAD

**Issue by mhosman** [HaithemMosbahi/ngx-avatar#84]
In order to avoid message:

> ngx-avatar@3.7.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by blindsz** [comment]
Can someone please update this? Thanks!

**Comment by maguro** [comment]
fyi https://github.com/HaithemMosbahi/ngx-avatar/pull/85

**Comment by chadbr** [comment]
He hasn't done anything on github since Nov...

Might be time to fork...

¯\_(ツ)_/¯

**Comment by blindsz** [comment]
Anyone that can update this? Thanks!

**Comment by mhosman** [comment]
Yes @chadbr, no news from this user since November. Maybe some of the direct collaborators of this project could fork this one.

**Comment by mhosman** [comment]
Another problem with Angular 9.0:

`WARNING in Entry point 'ngx-avatar' contains deep imports into '/Users/xxxxxxxx/Documents/GitHub/project/node_modules/ts-md5/dist/md5'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

**Comment by blindsz** [comment]
Still nothing??

**Comment by ea20140129** [comment]
Is there an ETA for getting this module to Angular 9.0?

**Comment by davequested** [comment]
+1 

`Seeing ngx-avatar@3.7.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.`

and 

`Entry point 'ngx-avatar' contains deep imports into '/Users/dave/Documents/code/apps/mobile/node_modules/ts-md5/dist/md5'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

**Comment by odahcam** [comment]
Nope, no ETA, no nothing. We are no an organization so we do not have a schedule or anything like that, this is just old free open source made to help the community, sorry. I'm helping to maintain things in here as I can and pushing forward some changes, but I'm no package maintainer in NPM, so even if I merge some PR in here, it doesn't mean it will get published, sorry again. Until @HaithemMosbahi is back I believe no new versions will get published. You're making an awesome job contributing and making PRs to the repo tho, thank you all.

**Comment by HaithemMosbahi** [comment]
New version is released with Angular 9 support => 4.0.0
Sorry guys for the delay

**Comment by mhosman** [comment]
Great news man!! Glad to have you back.
