### ISSUE TITLE
Migrate async handling to specific classes

### ISSUE THREAD

**Issue by sweko** [HaithemMosbahi/ngx-avatar#9]
Right now, the code that handles the async avatar sources is half in the relevant class, i.e. `google.ts`, and half in a method in `utils.ts` (`_extractGoogleAvatar`).
Also, the definition of which sources are async, and which are direct is held in `utils.ts`. 

It would be better if that definition, as well as the handling is moved to the relevant class.

**Comment by HaithemMosbahi** [comment]
This refactoring has been included in version 2.4.0. Async sources are much more cleaner now thanks to @sweko :)
